Bab 6/webChatbot/chatbot/urls.py
from django.urls import path 
from chatbot import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
	path('', views.index, name='chatbot'),
	path('update/<int:id>', views.update, name='update'),
	path('delete/<int:id>', views.delete, name='delete'),

	path('res', views.indexresp, name='chatbotresp'),
	path('updateres/<int:id>', views.updateresp, name='updateresp'),
	path('deleteres/<int:id>', views.deleteresp, name='deleteresp'),
]

Bab 6/webChatbot/search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
	path('chatbot/', views.search, name='search'),
	path('chatbot/res/', views.searchr, name='searchr'),
]

Bab 6/webChatbot/webChatbot/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.index, name='indexuser'),
    path('login', views.signin, name="login"),
	path('logout', views.signout, name="logout"),
	path('register', views.register, name="register"),
    path('search/', include('search.urls')),

    #path app
    path('chatbot/', include('chatbot.urls')),
]

Bab 6/webChatbot/chatbot/models.py
from djongo import models

class Respon(models.Model):
    tag = models.CharField(max_length=50)
    patterns = models.CharField(max_length=400)

class Responses(models.Model):
    tag = models.CharField(max_length=50)
    responses = models.CharField(max_length=400)

Bab 6/webChatbot/search/models.py
from django.db import models

# Create your models here.

Bab 6/webChatbot/chatbot/forms.py
from django import forms
from .models import Respon, Responses

class ResponCreateForm(forms.ModelForm):
	
	class Meta:
		model = Respon
		fields = ['tag', "patterns"]

class ResponsesCreateForm(forms.ModelForm):
	
	class Meta:
		model = Responses
		fields = ['tag','responses']

Bab 6/webChatbot/webChatbot/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = [
            'name',
            'last_name',
            'email',
            'username',
            'password1',
            'password2'
        ]
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

Bab 6/webChatbot/chatbot/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Respon, Responses
from chatbot.forms import ResponCreateForm, ResponsesCreateForm
from django.contrib.auth.decorators import login_required


@login_required(login_url='/login')
def index(request):
  data = Respon.objects.all()
  paginator = Paginator(data, 15) # Show 25 contacts per page.
  page = request.GET.get('page')
  page_res = paginator.get_page(page)
  
  form = ResponCreateForm(request.POST)
  if request.method == 'POST':
    form = ResponCreateForm(request.POST)

    if form.is_valid():
      form.save(commit=True)
      return redirect('../chatbot')
    else:
      print("error")


  context = {
	'subjudul' : "Manage Input Chatbot",
  'data' : data,
  'page_res' : page_res,
  'form' : form,
  }
  
  return render(request,'chatbot/index.html',context)


@login_required(login_url='/login')
def indexresp(request):
  data = Responses.objects.all()
  paginator = Paginator(data, 10) # Show 25 contacts per page.
  page = request.GET.get('page')
  page_res = paginator.get_page(page)
  
  form = ResponsesCreateForm()
  if request.method == 'POST':
    form = ResponsesCreateForm(request.POST)

    if form.is_valid():
      form.save(commit=True)
      return redirect('../chatbot/res')
    else:
      print("error")


  context = {
	'subjudul' : "Manage Respon Chatbot",
  'dataresp' : data,
  'page_res' : page_res,
  'formresp' : form,
  }
  
  return render(request,'chatbot/indexresp.html',context)

@login_required(login_url='/login')
def updateresp(request, id):
  updtresp = get_object_or_404(Responses, id=id)
  dataresp = Responses.objects.all()

  dt = {
    'tag' : updtresp.tag,
    'responses' : updtresp.responses,
  }

  form = ResponsesCreateForm(request.POST or None, instance=updtresp)
  if request.method == 'POST':
    if form.is_valid():
      form.save()
    return redirect('chatbotresp')
    

  context = {
	'subjudul' : "Manage Chatbot",
  'data' : dataresp,
  'form' : form,
  }
    
  return render(request,'chatbot/update_viewresp.html',context)

@login_required(login_url='/login')
def update(request, id):
  updt = get_object_or_404(Respon, id=id)
  data = Respon.objects.all()

  dt = {
    'tag' : updt.tag,
    'patterns' : updt.patterns,
  }

  form = ResponCreateForm(request.POST or None, instance=updt)
  if request.method == 'POST':
    if form.is_valid():
      form.save()
    return redirect('chatbot')
    

  context = {
	'subjudul' : "Manage Chatbot",
  'data' : data,
  'form' : form,
  }
    
  return render(request,'chatbot/update_view.html',context)

@login_required(login_url='/login')
def delete(request, id):
  delt = Respon.objects.get(id=id)
  delt.delete()
  return redirect('chatbot')

@login_required(login_url='/login')
def deleteresp(request, id):
  delt = Responses.objects.get(id=id)
  delt.delete()
  return redirect('chatbotresp')

Bab 6/webChatbot/search/views.py
from django.shortcuts import render
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from chatbot.models import Respon, Responses

def search(request):
    search = request.GET.get('q')
    data = Respon.objects.all()

    if search:
        data = data.filter(
            Q(patterns__icontains=search)|Q(tag__icontains=search)
        )

    
    
    context = {
        "subjudul":"Pencarian",
        "data": data,
        "search": search,
    }
    
    return render(request, 'chatbot/index.html', context)

def searchr(request):
    searchr = request.GET.get('j')
    page_res = Responses.objects.all()

    if searchr:
        page_res = page_res.filter(
            Q(tag__icontains=searchr)
        )

    
    
    context = {
        "subjudul":"Pencarian",
        "page_res": page_res,
        "searchr": searchr,
    }
    
    return render(request, 'chatbot/indexresp.html', context)

Bab 6/webChatbot/webChatbot/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegistrationForm


@login_required(login_url='/login')
def index(request):
	context = {
		'subjudul' : "Dashboard",
	}

	return render(request,'index.html',context)


def signin(request):
    if request.user.is_authenticated:
        return redirect('indexuser')
    else:
        if request.method == "POST":
            user = request.POST.get('user')
            password = request.POST.get('pass')
            auth = authenticate(request, username=user, password=password)
            if auth is not None:
                login(request, auth)
                return redirect('indexuser')
            else:
            	messages.error(request, 'username and password doesn\'t match')

    return render(request, 'login.html')



@login_required(login_url='/login')
def signout(request):
    logout(request)
    return redirect('login')	


def register(request):
    form = RegistrationForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('login')

    return render(request, 'register.html', {"form": form})

Bab 6/webChatbot/chatbot/templates/chatbot/index.html
{% extends "base.html" %}
{% load static %}

{% block search %}
<!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
        action="{% url 'search:search' %}" method="GET">
        <div class="input-group">
            <input type="search" class="form-control bg-light border-0 small" placeholder="Search by Tags and Inputs..."
                aria-label="Search" aria-describedby="basic-addon2"  name="q" value="{{search}}">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>                        
{% endblock search %}

{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Manage Input Chatbot</h1>
</div>

<div class="col">
    <div class="card border-bottom-primary shadow">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="formGroupExampleInput2">Tag</label>
                    <select class="form-control" name="tag" id="tag">
                        <option selected disabled></option>
                        <option value="salam">Salam</option>
                        <option value="nama">Nama</option>
                        <option value="umur">Umur</option>
                        <option value="alamat">Alamat</option>
                        <option value="pendidikan_terakhir">Pendidikan terakhir</option>
                        <option value="pengalaman">Pengalaman</option>
                        <option value="skill">Skill</option>
                        <option value="kelebihan">Kelebihan</option>
                        <option value="kekurangan">Kekurangan</option>
                        <option value="tentang_perusahaan">Tentang perusahaan</option>
                        <option value="alasan_menerima">Alasan menerima</option>
                        <option value="posisi">Posisi</option>
                        <option value="gaji">Gaji</option>
                        <option value="kontribusi">Kontribusi</option>
                        <option value="info_loker">Info loker</option>
                        <option value="penutup">Penutup</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput2">Inputs</label>
                    <input type="text" class="form-control" name="patterns" id="patterns">
                </div>
                <hr class="mb-4">
                <button type="submit" class="btn btn-primary btn-block">Submit</button>
            </form>
        </div>
    </div>

    <br><hr>

    <div class="card border-bottom-primary shadow">
        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Tags</th>
                        <th scope="col">Inputs</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for respon in page_res %}
                    <tr>
                        <td>{{ respon.tag }}</td>
                        <td>{{ respon.patterns }}</td>
                        <td>                            
                            <a href="{% url 'update' id=respon.id %}" class="btn btn-outline-warning btn-sm">Update</a>
                            <br><br>
                            <a href="{% url 'delete' id=respon.id %}" class="btn btn-outline-danger btn-sm">Delete</a>
                        
                            <!-- Delete Modal-->
                            <!-- <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Are you sure for delete?</h5>
                                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">Select "Delete" below if you are ready to delete your tag.</div>
                                        <div class="modal-footer">
                                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                                            <a class="btn btn-primary" href="{% url 'delete' id=respon.id %}">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div> -->
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <!-- Pagination -->
            <div class="pagination">
                <span class="step-links">
                    {% if page_res.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_res.previous_page_number }}">previous</a>
                    {% endif %}
                    
                    <span class="current">
                        Page {{ page_res.number }} of {{ page_res.paginator.num_pages }}.
                    </span>
            
                    {% if page_res.has_next %}
                        <a href="?page={{ page_res.next_page_number }}">next</a>
                        <a href="?page={{ page_res.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>

        </div>
    </div>
</div>
{% endblock content %}

Bab 6/webChatbot/chatbot/templates/chatbot/indexresp.html
{% extends "base.html" %}
{% load static %}

{% block search %}
<!-- Sidebar Toggle (Topbar) -->
<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
</button>

<!-- Topbar Search -->
<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
    action="{% url 'search:searchr' %}" method="GET">
    <div class="input-group">
        <input type="search" class="form-control bg-light border-0 small" placeholder="Search by Tags..."
            aria-label="Search" aria-describedby="basic-addon2"  name="j" value="{{searchr}}">
        <div class="input-group-append">
            <button class="btn btn-primary" type="submit">
                <i class="fas fa-search fa-sm"></i>
            </button>
        </div>
    </div>
</form>                        
{% endblock search %}

{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Manage Respon Chatbot</h1>
</div>

<div class="col">
    <div class="card border-bottom-primary shadow">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="formGroupExampleInput2">Tag</label>
                    <select class="form-control" name="tag" id="tag">
                        <option selected disabled></option>
                        <option value="salam">Salam</option>
                        <option value="nama">Nama</option>
                        <option value="umur">Umur</option>
                        <option value="alamat">Alamat</option>
                        <option value="pendidikan_terakhir">Pendidikan terakhir</option>
                        <option value="pengalaman">Pengalaman</option>
                        <option value="skill">Skill</option>
                        <option value="kelebihan">Kelebihan</option>
                        <option value="kekurangan">Kekurangan</option>
                        <option value="tentang_perusahaan">Tentang perusahaan</option>
                        <option value="alasan_menerima">Alasan menerima</option>
                        <option value="posisi">Posisi</option>
                        <option value="gaji">Gaji</option>
                        <option value="kontribusi">Kontribusi</option>
                        <option value="info_loker">Info loker</option>
                        <option value="penutup">Penutup</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="formGroupExampleInput2">Responses</label>
                    <input type="text" class="form-control" name="responses" id="responses">
                </div>
                <hr class="mb-4">
                <button type="submit" class="btn btn-primary btn-block">Submit</button>
            </form>
        </div>
    </div>

    <br><hr>

    <div class="card border-bottom-primary shadow">
        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Tags</th>
                        <th scope="col">Responses</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for respon in page_res %}
                    <tr>
                        <td>{{ respon.tag }}</td>
                        <td>{{ respon.responses }}</td>
                        <td>                            
                            <a href="{% url 'updateresp' id=respon.id %}" class="btn btn-outline-warning btn-sm">Update</a>
                            <br><br>
                            <a href="{% url 'deleteresp' id=respon.id %}" class="btn btn-outline-danger btn-sm">Delete</a>
                        
                            <!-- Delete Modal-->
                            <!-- <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Are you sure for delete?</h5>
                                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">Select "Delete" below if you are ready to delete your tag.</div>
                                        <div class="modal-footer">
                                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                                            <a class="btn btn-primary" href="{% url 'delete' id=respon.id %}">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div> -->
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <!-- Pagination -->
            <div class="pagination">
                <span class="step-links">
                    {% if page_res.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_res.previous_page_number }}">previous</a>
                    {% endif %}
                    
                    <span class="current">
                        Page {{ page_res.number }} of {{ page_res.paginator.num_pages }}.
                    </span>
            
                    {% if page_res.has_next %}
                        <a href="?page={{ page_res.next_page_number }}">next</a>
                        <a href="?page={{ page_res.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>

        </div>
    </div>
</div>
{% endblock content %}

Bab 6/webChatbot/chatbot/templates/chatbot/update_view.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Update Input Chatbot</h1>
</div>

<div class="col">
    <div class="card border-bottom-primary shadow">
        <div class="card-body">
            <form method="POST">
                <!-- Security token by Django -->
                {% csrf_token %}
        
                <!-- form as paragraph -->
                <div class="mb-4">
                {{ form.tag|as_crispy_field }}
                </div>
                <div class="mb-4">
                {{ form.patterns|as_crispy_field }}
                </div>

                <hr class="mb-4">
                <button type="submit" class="btn btn-primary btn-block">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

Bab 6/webChatbot/chatbot/templates/chatbot/update_viewresp.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Update Respon Chatbot</h1>
</div>

<div class="col">
    <div class="card border-bottom-primary shadow">
        <div class="card-body">
            <form method="POST">
                <!-- Security token by Django -->
                {% csrf_token %}
        
                <!-- form as paragraph -->
                <div class="mb-4">
                {{ form.tag|as_crispy_field }}
                </div>
                <div class="mb-4">
                {{ form.responses|as_crispy_field }}
                </div>

                <hr class="mb-4">
                <button type="submit" class="btn btn-primary btn-block">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

Bab 6/webChatbot/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>AIBot - {{ subjudul }}</title>

    {% block app_css %}	
    <!-- Custom fonts for this template-->
    <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="/static/css/sb-admin-2.min.css" rel="stylesheet">
    {% endblock app_css %}

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        {% include "snippets/sidebar.html" %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    {% block search %}
                        
                    {% endblock search %}

                    {% include "snippets/navbar.html" %}
                </nav>
                <!-- End of Topbar -->

                <!-- Messages -->
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible text-center" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button> 
                    {{ message }}
                </div>
                {% endfor %}

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    {% block content %}
					
		            {% endblock content%}

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            {% include "snippets/footer.html" %}

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/static/js/sb-admin-2.min.js"></script>

</body>

</html>

Bab 6/webChatbot/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- Page Heading -->
<!-- <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
</div> -->

<!-- Content Row -->

<div class="row">

    <div class="col">

        <!-- Illustrations -->
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="text-center">
                    <img class="img-fluid" style="height: 7cm; width: 30cm;"
                        src="{% static 'img/bgaaa.jpg' %}" alt="...">
                </div>
            </div>
        </div>

        <!-- Illustrations -->
        <div class="card-deck">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h5 class="m-0 font-weight-bold text-dark">Siapa itu AIBot?</h5>
                </div>
                <div class="card-body">
                    <div class="text-center">
                        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 15rem;"
                            src="{% static 'img/chatting.svg' %}" alt="...">
                    </div>
                    <p>AIBot merupakan sebuah chatbot yang digunakan dalam membantu proses seleksi kandidat karyawan
                        dalam tahapan wawancara. Dengan AIBot, kandidat karyawan akan melakukan proses wawancara dengan 
                        suatu machine sehingga proses wawancara akan terdigitalisasi dan terotomatisasi.</p>
                </div>
            </div>

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h5 class="m-0 font-weight-bold text-dark">Cara Penggunaan Bot</h5>
                </div>
                <div class="card-body">
                    <div class="text-center">
                        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;"
                            src="{% static 'img/user_flow.svg' %}" alt="...">
                    </div>
                    <br>
                    <p>Penggunaan dari AIBot dapat dinikmati oleh pengguna pada platform Telegram.
                        Pengguna tinggal memulai percakapan dengan mengirimkan perintah "/start" atau
                        memilih perintah "/start" untuk pengguna baru. Selanjutnya pengguna tinggal mengikuti
                        alur percakapan yang dikirimkan oleh AIBot.</p>
                        <p>Untuk mengakses AIBot pada Telegram, silahkan klik link berikut <a href="https://t.me/InterviewCoBot">AIBot</a></p>
                </div>
            </div>

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h5 class="m-0 font-weight-bold text-dark">Cara Penggunaan Web</h5>
                </div>
                <div class="card-body">
                    <div class="text-center">
                        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 14rem;"
                            src="{% static 'img/web.svg' %}" alt="...">
                    </div>
                    <p>Penggunaan web Management Chatbot Wawancara Kerja ini, pengguna harus melakukan login atau registrasi
                        terlebih dahulu. Kemudian pengguna akan disajikan halaman Dashboard sebagai halaman awal. Jika pengguna
                        ingin menambah data inputs atau patterns pada chatbot, pengguna tinggal masuk pada halaman chatbot melalui tab disebelah kiri layar.
                        Apabila pengguna ingin menambah data respon pada chatbot, pengguna tinggal masuk pada halaman chatbot respon melalui tab disebelah kiri layar.
                        Pengguna juga dapat melakukan edit dan hapus data didalam halaman tersebut.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content%}

Bab 6/webChatbot/templates/snippets/footer.html
{% load static %}
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; AIBot 2022</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->